### ISSUE TITLE
[EPIC] Story page construction

### ISSUE THREAD

**Issue by Jeevan-Kishore** [Jeevan-Kishore/mediaone-poc#1]
## Story page creation 

- [ ] Loading google fonts with [swap](https://stackoverflow.com/questions/56385231/being-penalized-on-page-speed-by-google-fonts)
- [ ] Combine API's of sketches
	- [ ] story by slug
	- [ ] related stories
	- [ ] trending stories
- [ ] Implement header with logos
- [ ] Implement DFP ad's
- [ ] Implement Infinite pagination
